In [1]:
from numpy import *

In [57]:
# Ideal functions deal with redian not degrees.
a = sin(30)
b = cos(30)
c = tan(30)
print(a,b,c)

-0.9880316240928618 0.15425144988758405 -6.405331196646276


In [60]:
a = sin(30*pi/180)
b = cos(30*pi/180)
c = tan(30*pi/180)
print(a)
print(b) 
print(c)

0.49999999999999994
0.8660254037844387
0.5773502691896257


In [61]:
# ٌRounding.
a = round(3.68528)
b = round(3.68528,1)
c = round(3.38528,2)
d = round(3.58528,3)
print(a)
print(b)
print(c)
print(d)

4
3.7
3.39
3.585


In [62]:
# Rounding higher(ceil) or lower (floor).
a = floor(3.68528) 
b = ceil(3.38528)
print(a)
print(b)

3.0
4.0


In [63]:
# mod for modulas.
a = mod(20,7) 
b = power(2,5)
print(a) 
print(b)

6
32


In [64]:
# Use array function to convert list to matrix.
a = [2,3,6,5,4,7,8]
b = array(a)
print(a)
print(b)

[2, 3, 6, 5, 4, 7, 8]
[2 3 6 5 4 7 8]


In [65]:
# matrix (3,3).
a = [[1,2,3],[5,3,6],[9,6,5]]
b = array(a)
print(a)
print(b)

[[1, 2, 3], [5, 3, 6], [9, 6, 5]]
[[1 2 3]
 [5 3 6]
 [9 6 5]]


In [66]:
# Use range to make matrix.
a = array([range(i, i + 3)
for i in [2, 4, 6]])
print(a)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [67]:
# Defination of Variables.
a = array([('x',3,4.2),('y',4,5.3),('z',5,6.3)],
          dtype = [('name','U5'),('number','i2'),('value','f4')])
print(a)

[('x', 3, 4.2) ('y', 4, 5.3) ('z', 5, 6.3)]


In [68]:
# Empty matrix.
a = empty((2,3)) # 2 is number of rows , 3 is number of columns.
print(a)

[[2.12199579e-314 6.36598737e-314 1.06099790e-313]
 [1.48539705e-313 1.90979621e-313 2.33419537e-313]]


In [69]:
# Uniform function: Random value.
a = random.uniform(1,10)
b = random.uniform(1,10,20)
print(a)
print('-------------------------')
print(b)
print('-------------------------')

5.275717387762862
-------------------------
[4.63539967 5.78838532 7.43305094 6.77817172 7.81705517 1.55028282
 2.54378481 7.25404858 7.24207275 9.46109042 3.33753785 4.29002392
 8.5191932  5.21005267 7.88533115 4.50257674 9.22414167 2.49807775
 5.51172799 5.02788698]
-------------------------


In [70]:
# Convert to list.
c = list(b)
print(c)

[4.6353996727964955, 5.788385315410977, 7.433050943707513, 6.7781717218312565, 7.817055173005205, 1.5502828185384216, 2.5437848140445656, 7.254048584920625, 7.242072745642831, 9.461090424508594, 3.337537852222976, 4.290023919473347, 8.519193200714522, 5.210052670478994, 7.885331153802053, 4.502576736530578, 9.224141673918814, 2.498077749659318, 5.511727988829841, 5.02788697712487]


In [71]:
# Make a matrix with random values between 0,1
a = random.random((2,3))
print(a)

[[0.29145045 0.43762688 0.79983274]
 [0.56609945 0.00187106 0.34476896]]


In [72]:
# Normal function: it distribute normally between 0,1 (10 times).
a = random.normal(0,1,10)
print(a)

[-0.61959543 -0.31571111  0.92124655  0.44682556  0.00390882  0.00326794
 -0.41694023 -0.4375525   1.03067883  1.74138305]


In [73]:
# RandInt function: get any integer value between 0,150
a = random.randint(150)
print(a)

66


In [74]:
# Get any integer value between 0,5 (7 times).
a = random.randint(5, size=7)
print(a)

[2 0 3 2 2 3 3]


In [75]:
# Get any integer value between 5,20 (7 times).
a = random.randint(5,20, size=7) 
print(a)

[17  6 19  9  6 17 19]


In [76]:
# Get any integer value between 0,10
a = random.randint(0, 10, (3, 3))
print(a)

[[0 4 8]
 [3 4 9]
 [4 0 2]]


In [77]:
# Get any integer value between 5,10 (3 matrices) be (4,5). 
a = random.randint(5,10, size=(3, 4, 5)) 
print(a)

[[[8 5 9 9 6]
  [7 8 8 6 7]
  [6 5 7 7 5]
  [9 8 5 6 5]]

 [[5 5 9 7 8]
  [9 5 9 8 8]
  [9 5 9 7 6]
  [6 7 8 7 7]]

 [[6 9 8 8 7]
  [9 6 6 7 9]
  [6 8 6 5 7]
  [6 6 7 9 9]]]


In [78]:
# Get any integer value between 1,60 (25 times) then reshape it to matrix (5,5).
a = random.randint(1,60,25)
b = reshape(a,(5,5))
print(a)
print(b)

[16 20 39 53  2  2 54 16 28 30 33 37 26 53 27 18 16 36 35 30 33  1  4 30
 51]
[[16 20 39 53  2]
 [ 2 54 16 28 30]
 [33 37 26 53 27]
 [18 16 36 35 30]
 [33  1  4 30 51]]


In [79]:
# Random numbers (15 times).
a = random.rand(15) 
print(a)

[0.60723448 0.6476839  0.45386926 0.91109513 0.23313707 0.83870361
 0.22066304 0.72834021 0.50829794 0.77827276 0.82927491 0.84496405
 0.05530003 0.50386149 0.01478985]


In [80]:
# Random numbers with matrix (5,3).
a = random.rand(5,3)
print(a)

[[0.14991841 0.12427026 0.14254606]
 [0.79766841 0.78547135 0.63473452]
 [0.81838346 0.56652475 0.18352945]
 [0.93592573 0.0148192  0.39902046]
 [0.40424027 0.75779562 0.09942307]]


In [81]:
# Random numbers with 5 matrices (3,2).
a = random.rand(5,3,2)
print(a)

[[[0.41033242 0.7063434 ]
  [0.41835544 0.2946406 ]
  [0.34891864 0.32090821]]

 [[0.84334964 0.11561896]
  [0.20821223 0.65260843]
  [0.49671581 0.49851679]]

 [[0.90722532 0.17389357]
  [0.47878829 0.2980763 ]
  [0.77001445 0.48372405]]

 [[0.50155482 0.810997  ]
  [0.40492765 0.73075129]
  [0.12635451 0.39579616]]

 [[0.66876419 0.92606162]
  [0.17085335 0.15613766]
  [0.52361056 0.3127123 ]]]


In [82]:
# Choice function choose any value of given list.
y=[1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
a = random.choice(y)
print(a)

5


In [83]:
# Choice function choose any value of given list 5 times.
y=[1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
a = random.choice(y,size=5)
print(a)

[9 2 6 6 8]


In [84]:
# Shuffle function make a random changes in given list.
y=[1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
print(y)
random.shuffle(y)
print(y)

[1, 2, 3, 6, 9, 8, 5, 4, 7, 8, 9, 6, 5, 9, 6]
[6, 8, 5, 6, 9, 9, 3, 1, 8, 2, 7, 4, 9, 5, 6]


In [85]:
# Zeros function makes 8 zeros in matrix(1,0).
# Ones function makes 10 ones in matrix(1,0).
a = zeros(8)
b = ones(10)
print(a)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [86]:
# Zeros function makes 10 zeros in matrix(3,5).
# Ones function makes 10 ones in matrix(6,8).
a = zeros((3,5))
b = ones((6,8))
print(a)
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [87]:
# Zeros function makes 10 zeros in 2 matrices(3,2).
# Ones function makes 10 ones in 2 matrices(3,2).
a = zeros((2,3,2))
b = ones((2,3,2))
print(a)
print(b)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [89]:
# Eye function : Makes a matrix with given number (5,5)zeros ,then makes ones in inner diagonals.
a = eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [90]:
# Full function : makes a matrix(3,5) with a given number(35).
a = full((3, 5), 35)
print(a)

[[35 35 35 35 35]
 [35 35 35 35 35]
 [35 35 35 35 35]]


In [91]:
# Arrange function : arrange from 0 to given number(18),(27).
# Writes a matrix with a given dimension(3,6),(3,3)3 times.
a = arange(18).reshape(3,6)
b = arange(27).reshape(3,3,3)
print(a)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [92]:
# write a numbers that distributed equally between given numbers(0,30) 50 times ,and (0,100) 5 times. 
b =linspace(0,30)
c =linspace(0,100,5)
print(b)
print(c)

[ 0.          0.6122449   1.2244898   1.83673469  2.44897959  3.06122449
  3.67346939  4.28571429  4.89795918  5.51020408  6.12244898  6.73469388
  7.34693878  7.95918367  8.57142857  9.18367347  9.79591837 10.40816327
 11.02040816 11.63265306 12.24489796 12.85714286 13.46938776 14.08163265
 14.69387755 15.30612245 15.91836735 16.53061224 17.14285714 17.75510204
 18.36734694 18.97959184 19.59183673 20.20408163 20.81632653 21.42857143
 22.04081633 22.65306122 23.26530612 23.87755102 24.48979592 25.10204082
 25.71428571 26.32653061 26.93877551 27.55102041 28.16326531 28.7755102
 29.3877551  30.        ]
[  0.  25.  50.  75. 100.]


In [93]:
b =linspace(0,30,12).reshape(3,4)
c =linspace(0,100,27).reshape(3,3,3)
print(b)
print(c)

[[ 0.          2.72727273  5.45454545  8.18181818]
 [10.90909091 13.63636364 16.36363636 19.09090909]
 [21.81818182 24.54545455 27.27272727 30.        ]]
[[[  0.           3.84615385   7.69230769]
  [ 11.53846154  15.38461538  19.23076923]
  [ 23.07692308  26.92307692  30.76923077]]

 [[ 34.61538462  38.46153846  42.30769231]
  [ 46.15384615  50.          53.84615385]
  [ 57.69230769  61.53846154  65.38461538]]

 [[ 69.23076923  73.07692308  76.92307692]
  [ 80.76923077  84.61538462  88.46153846]
  [ 92.30769231  96.15384615 100.        ]]]


In [94]:
# Makes a matrix zeros(5,5):first given number ,and then write a diagonal as a given numbers.
a = diag(array([5,12,4,-1,3]))
b = diag(array([5,12,4,-1,3]),k=3) # k=3 means : add 3 zeros columns to the left (by default).
print(a)
print('-------------------------')
print(b)
print('-------------------------')

[[ 5  0  0  0  0]
 [ 0 12  0  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0 -1  0]
 [ 0  0  0  0  3]]
-------------------------
[[ 0  0  0  5  0  0  0  0]
 [ 0  0  0  0 12  0  0  0]
 [ 0  0  0  0  0  4  0  0]
 [ 0  0  0  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0  3]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
-------------------------


In [95]:
# Counts the numbers that is not zero.
a = random.randint(0,10,(3,3))
b = count_nonzero(a)
print(a)
print(b)

[[8 2 7]
 [9 8 2]
 [9 5 4]]
9


In [96]:
a = random.randint(0,10,(3,3))
b = count_nonzero(a>5)
c = count_nonzero(a<8)
print(a)
print(b)
print(c)

[[3 6 3]
 [4 5 8]
 [3 9 8]]
4
6


In [97]:
# axis = 1 means that count the rows.
a = random.randint(0,10,(3,3))
b = count_nonzero(a>5,axis=1)
c = count_nonzero(a<8,axis=1)
print(a)
print(b)
print(c)

[[2 6 4]
 [6 3 3]
 [9 3 4]]
[1 1 1]
[3 3 2]


In [98]:
# axis = 0 means that count the columns.
a = random.randint(0,10,(3,3))
b = count_nonzero(a>5,axis=0)
c = count_nonzero(a<8,axis=0)
print(a)
print(b)
print(c)

[[5 7 7]
 [9 7 6]
 [0 5 4]]
[1 2 2]
[2 3 3]


In [99]:
# any means OR .
a = random.randint(0,10,(3,3))
b = any(a>5)
print(a)
print(b)

[[1 1 0]
 [0 1 0]
 [0 6 4]]
True


In [100]:
a = random.randint(0,10,(3,3))
b = any(a>5,axis=1)
print(a)
print(b)

[[5 5 3]
 [3 8 5]
 [3 0 2]]
[False  True False]


In [101]:
# all means AND . 
a = random.randint(0,10,(3,3))
b = all(a>5)
print(a)
print(b)

[[2 5 5]
 [9 3 0]
 [4 9 6]]
False


In [102]:
a = random.randint(0,10,(3,3))
b = all(a>5,axis=0)
print(a)
print(b)

[[9 7 1]
 [1 5 7]
 [5 9 7]]
[False False False]


In [17]:
# (axis = 1) == rows
# (axis = 0) == columns

In [18]:
# any = OR
# all = AND 

In [103]:
a =random.randint(5,20, size=9).reshape(3,3)
b = a>10
c = a<15
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[[19  9 18]
 [15 16  8]
 [ 5 13 13]]
-------------------------
[[ True False  True]
 [ True  True False]
 [False  True  True]]
-------------------------
[[False  True False]
 [False False  True]
 [ True  True  True]]


In [104]:
# a[b] == print all trues number in b. 
a =random.randint(5,20, size=9).reshape(3,3)
b = a>10
c = a<15
d = a[b]
e = a[c]
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

[[14  5 19]
 [14 15  5]
 [ 5  5 17]]
-------------------------
[[ True False  True]
 [ True  True False]
 [False False  True]]
-------------------------
[[ True  True False]
 [ True False  True]
 [ True  True False]]
-------------------------
[14 19 14 15 17]
-------------------------
[14  5 14  5  5  5]


In [105]:
# isclose with rtol means that a,b && a,c if equal print true ,else print false. 
a = arange(9).reshape(3,3)
b = arange(9).reshape(3,3)
c = 2*b
d = isclose(a,b,rtol = 0.1)
e = isclose(a,c,rtol = 0.1)
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
-------------------------
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
-------------------------
[[ True False False]
 [False False False]
 [False False False]]


In [106]:
# Multiply a * 10 .
a = arange(5)
b = empty(5)
multiply(a, 10, out=b)
print(a)
print(b)

[0 1 2 3 4]
[ 0. 10. 20. 30. 40.]


In [107]:
# a power 4 .
a = arange(5)
b = empty(5)
power(a, 4, out=b)
print(a)
print(b)

[0 1 2 3 4]
[  0.   1.  16.  81. 256.]


In [108]:
# Sum of matrix values .
a = arange(15)
b = add.reduce(a)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
105


In [109]:
a = [1,2,3,4,5,6,7,8,9,10]
b = array(a)
c = add.reduce(b) 
print(a)
print(b)
print(c)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]
55


In [110]:
a = arange(2,8)
b = multiply.reduce(a)
print(a)
print(b)

[2 3 4 5 6 7]
5040


In [111]:
# That makes a first value multiply the whole matrix then second and so on .
a = arange(2,8)
b = multiply.outer(a,a)
print(a)
print(b)

[2 3 4 5 6 7]
[[ 4  6  8 10 12 14]
 [ 6  9 12 15 18 21]
 [ 8 12 16 20 24 28]
 [10 15 20 25 30 35]
 [12 18 24 30 36 42]
 [14 21 28 35 42 49]]


In [112]:
# That makes to add the previous values , ex: when get the sum of 10 : (4+3+2+1+0)=10 and so on.
a = arange(10)
b = add.accumulate(a)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  3  6 10 15 21 28 36 45]


In [113]:
a = arange(2,8)
b = multiply.accumulate(a)
print(a)
print(b)

[2 3 4 5 6 7]
[   2    6   24  120  720 5040]


In [114]:
# (d = len(c)) after reshape to know the size of rows.
a = arange(12)
b = len(a)
c = a.reshape(3,4)
d = len(c)
print(a)
print(b)
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
12
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
3


In [115]:
# Note:
# the numbers of rows and columns in reshape should equal the number of component that entered => like arrange(12).

In [116]:
# (d = c.size) to know the size of the indexes in the matrix.
a = arange(12)
b = a.size
c = a.reshape(3,4)
d = c.size
print(a)
print(b)
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
12
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
12


In [117]:
a = arange(12)
b = a.shape
c = a.reshape(3,4)
d = c.shape
print(a)
print(b)
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [118]:
# (shape == interval of matrix): like above example (3,4).
# (reshape == formating): like above example.

In [119]:
# ndim is abbreviation of number of dimension like (3,4) in reshape that is equal 2 and arrange(12) is equal 1.
a = arange(12)
b = a.ndim
c = a.reshape(3,4)
d = c.ndim
print(a)
print(b)
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2


In [120]:
# (U2): U is string , 2 is the number of each element in array. 
a = array(['a2','d2','g3','h4','j5'])
b = a.dtype
c = arange(12)
d = c.reshape(3,4)
e = d.dtype
print(a)
print(b)
print(c)
print(d)
print(e)

['a2' 'd2' 'g3' 'h4' 'j5']
<U2
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
int32


In [124]:
# Matrix formation
a = matrix('{} {};{} {}'.format(1,2,3,4)) # (2,2)
b = matrix('{} {} {};{} {} {}'.format(1,2,3,4,5,6)) # (2,3)
print(a)
print(b)
print("-------------------------")
c = a.shape
d = b.shape
print(c)
print(d)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]]
-------------------------
(2, 2)
(2, 3)


In [125]:
# Trace function : is used to calculate the sum of the diagonal elements of a given array or matrix.
a = arange(9)
b = a.reshape(3,3)
c = trace(b) # (0+4+8)=12
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
12


In [126]:
# linalg.det(): This function is used to compute the determinant of a square matrix,
# it takes a single argument, which is the input matrix, and returns the determinant value as a scalar.

#linalg.eig(): This function is used to compute the eigenvalues and eigenvectors of a square matrix.it takes a single 
# argument, which is the input matrix, and returns a tuple containing two arrays: the eigenvalues and the eigenvectors.

a = arange(9)
b = a.reshape(3,3)
c = linalg.det(b)
d = linalg.eig(b)
print(a)
print(b)
print(c)
print(d)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
0.0
(array([ 1.33484692e+01, -1.34846923e+00, -1.26963291e-15]), array([[ 0.16476382,  0.79969966,  0.40824829],
       [ 0.50577448,  0.10420579, -0.81649658],
       [ 0.84678513, -0.59128809,  0.40824829]]))


In [127]:
# (From : To-1)
a = arange(10)
c = a[3] # index 3
d = a[3:9] # index (3 to 8)
e = a[3:9:2] # index (3 to 8 and ignore one step after) ex: (3,4(ignored),5,6(ignored),7,8(ignored))= (3,5,7).
f = a[-1] # index (last)
g = a[-3] # index (before before last)
print(a)
print(c)
print(d)
print(e)
print(f)
print(g)

[0 1 2 3 4 5 6 7 8 9]
3
[3 4 5 6 7 8]
[3 5 7]
9
7


In [128]:
a = arange(36).reshape(6,6)
c = a[3]
d = a[3:9]
e = a[3:9:2]
f = a[-1]
g = a[-3]
print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[18 19 20 21 22 23]
-------------------------
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[[18 19 20 21 22 23]
 [30 31 32 33 34 35]]
-------------------------
[30 31 32 33 34 35]
-------------------------
[18 19 20 21 22 23]


In [130]:
a = arange(36).reshape(6,6)
c = a[3,1] # Value of index (3,1)=19
d = a[3,:] # Value of index (3,all row)
e = a[:,2] # Value of index (all column,2)
f = a[:,1:3] # Value of index (all column,1 to (3-1))
g = a[1:2,:] # Value of index (1,2 to all row) == as a[1:2]
print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)

[[ 6  7  8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
19
-------------------------
[18 19 20 21 22 23]
-------------------------
[ 2  8 14 20 26 32]
-------------------------
[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]]
-------------------------
[[ 6  7  8  9 10 11]]


In [131]:
a = arange(36).reshape(6,6)
c = a[3:4,1:5] # index of 3 in row ,column from index 1 to 4.
d = a[2:,3:] # index of 2 in row to end,column from index 3 to end.
e = a[:2,:3] # index from first row to 1,column from first to 2.
f = a[:,-1] # last column.
g = a[-1,:] # last row.
print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[[19 20 21 22]]
-------------------------
[[15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]
-------------------------
[[0 1 2]
 [6 7 8]]
-------------------------
[ 5 11 17 23 29 35]
-------------------------
[30 31 32 33 34 35]


In [132]:
a = arange(36).reshape(6,6)
c = a[::2,::3]
d = a[::-1,::-1] # convert from ascending to descending.
e = a[:2:-1,:3:-1]
f = a[2::2,3::3]
g = a[-1::,-1::]
print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[[ 0  3]
 [12 15]
 [24 27]]
-------------------------
[[35 34 33 32 31 30]
 [29 28 27 26 25 24]
 [23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]
-------------------------
[[35 34]
 [29 28]
 [23 22]]
-------------------------
[[15]
 [27]]
-------------------------
[[35]]


In [133]:
a = arange(16).reshape(4,4)
print(a)
a[2,3]=0
print(a)
a[:,3]=0
print(a)
a[2,:]=0
print(a)
a[:,:]=0
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10  0]
 [12 13 14 15]]
[[ 0  1  2  0]
 [ 4  5  6  0]
 [ 8  9 10  0]
 [12 13 14  0]]
[[ 0  1  2  0]
 [ 4  5  6  0]
 [ 0  0  0  0]
 [12 13 14  0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [134]:
a = arange(16).reshape(4,4)
print(a)
b = a[:,1:3]
print(b)
a[:,:] = 5
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[5 5]
 [5 5]
 [5 5]
 [5 5]]


In [135]:
a = arange(16).reshape(4,4)
print(a)
b = a[:,1:3].copy()
print(b)
a[:,:] = 5
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [136]:
a = arange(18).reshape(3,3,2)
c = a[1]
d = a[1,2]
e = a[2,2,1]
print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
-------------------------
[[ 6  7]
 [ 8  9]
 [10 11]]
-------------------------
[10 11]
-------------------------
17


In [137]:
x = [11,22,33,44,55,66,77,88]
x1, x2, x3 = split(x, (3,6)) # [0,1,2],[3,4,5],[6,7]
print(x1, x2, x3)
x1, x2, x3 = split(x, (1,5)) # [0],[1,2,3,4],[5,6,7]
print(x1, x2, x3)
x1, x2, x3 = split(x, (6,3)) # [0,1,2,3,4,5],[],[3,4,5,6,7]
print(x1, x2, x3)
x1, x2, x3 = split(x, (0,3)) # [],[0,1,2],[3,4,5,6,7]
print(x1, x2, x3)
x1, x2, x3 = split(x, (4,0)) # [0,1,2,3],[],[0,1,2,3,4,5,6,7]
print(x1, x2, x3)

[11 22 33] [44 55 66] [77 88]
[11] [22 33 44 55] [66 77 88]
[11 22 33 44 55 66] [] [44 55 66 77 88]
[] [11 22 33] [44 55 66 77 88]
[11 22 33 44] [] [11 22 33 44 55 66 77 88]


In [138]:
a = arange(16).reshape(4,4)
b = a[2][1]
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
9


In [139]:
# vstack : vertical stack => add a on b in matrix vertically.
a = arange(4).reshape(2,2)
b = 2*arange(4).reshape(2,2)
c = vstack((a,b))
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[[0 1]
 [2 3]]
-------------------------
[[0 2]
 [4 6]]
-------------------------
[[0 1]
 [2 3]
 [0 2]
 [4 6]]


In [140]:
# vhstack : horizontal stack => add a on b in matrix horizontaly. 
a = arange(4).reshape(2,2)
b = 2*arange(4).reshape(2,2)
c = hstack((a,b))
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[[0 1]
 [2 3]]
-------------------------
[[0 2]
 [4 6]]
-------------------------
[[0 1 0 2]
 [2 3 4 6]]


In [150]:
a = random.randint(5,20, size=9).reshape(3,3)
b = random.randint(5,20, size=9).reshape(3,3)
c = concatenate([a,b] , axis = 1) # add b to a in rows.
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')

[[14  7 13]
 [10  9  8]
 [16 12  7]]
-------------------------
[[ 7  6  9]
 [12  8  9]
 [ 7  5 16]]
-------------------------
[[14  7 13  7  6  9]
 [10  9  8 12  8  9]
 [16 12  7  7  5 16]]
-------------------------


In [151]:
a = random.randint(5,20, size=9).reshape(3,3)
b = a.max()
c = a.min()
d = argmax(a) # location of max in arrange
e = argmin(a) # location of min in arrange
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

[[ 9  8 19]
 [ 7 15  8]
 [ 9  7 11]]
-------------------------
19
-------------------------
7
-------------------------
2
-------------------------
3


In [152]:
a = random.randint(5,20, size=9).reshape(3,3)
b = var(a) # variance = mean(abs(x-x.mean) power 2)
c = cov(a) # covariance = (summation(xy)/n)-(summation(x)/n)(summation(y)/n)
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[[15 10 15]
 [ 8  5  9]
 [16 12 17]]
-------------------------
15.209876543209877
-------------------------
[[8.33333333 5.83333333 7.5       ]
 [5.83333333 4.33333333 5.5       ]
 [7.5        5.5        7.        ]]


In [4]:
a = random.randint(5,20, size=9).reshape(3,3)
b = random.randint(5,20, size=9).reshape(3,3)
c = sin(a)
d = b**2
e = log(a)
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

[[16 19  5]
 [ 7 15  7]
 [ 6 16  5]]
-------------------------
[[18  7  8]
 [12 19 15]
 [ 8  6 11]]
-------------------------
[[-0.28790332  0.14987721 -0.95892427]
 [ 0.6569866   0.65028784  0.6569866 ]
 [-0.2794155  -0.28790332 -0.95892427]]
-------------------------
[[324  49  64]
 [144 361 225]
 [ 64  36 121]]
-------------------------
[[2.77258872 2.94443898 1.60943791]
 [1.94591015 2.7080502  1.94591015]
 [1.79175947 2.77258872 1.60943791]]


In [5]:
a = random.randint(1,4, size=9).reshape(3,3)
b = random.randint(1,4, size=9).reshape(3,3)
c = dot(a,b)
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[[3 1 1]
 [2 3 1]
 [1 2 2]]
-------------------------
[[2 1 1]
 [1 1 1]
 [2 2 2]]
-------------------------
[[9 6 6]
 [9 7 7]
 [8 7 7]]


In [6]:
a = random.randint(5,20, size=9).reshape(3,3)
b = sum(a)
c = a.sum()
d = a.sum(axis = 1)  # Sum of rows
e = a.sum(axis = 0)  # Sum of columns
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

[[14  8 18]
 [10 16  7]
 [14 19 17]]
-------------------------
123
-------------------------
123
-------------------------
[40 33 50]
-------------------------
[38 43 42]


In [7]:
a = random.randint(5,20, size=9).reshape(3,3)
b = a.mean()  # Average or arithmetic mean  = (n1 + n2 + n3 + n4 + n5) / 5
c = a.std()   # Standared Deviation = sqrt(mean(abs(x-x.mean) power 2))
d = a.var()
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)

[[ 8 19  8]
 [12 16 15]
 [17 12  6]]
-------------------------
12.555555555555555
-------------------------
4.271640619275797
-------------------------
18.246913580246915


In [8]:
a = random.randint(5,20, size=9).reshape(3,3)
b = corrcoef(a)   # Relationship for every number to whole numbers.
print(a)
print('-------------------------')
print(b)
print('-------------------------')

[[13 18 15]
 [10  7 14]
 [17 15 16]]
-------------------------
[[ 1.         -0.52802    -0.99339927]
 [-0.52802     1.          0.4271211 ]
 [-0.99339927  0.4271211   1.        ]]
-------------------------


In [2]:
a = random.randint(5,20, size=9).reshape(3,3)
b = sort(a,axis=0)
c = sort(a,axis=1)
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')

[[19 12 13]
 [14 11 19]
 [12 12 14]]
-------------------------
[[12 11 13]
 [14 12 14]
 [19 12 19]]
-------------------------
[[12 13 19]
 [11 14 19]
 [12 12 14]]
-------------------------


In [4]:
# Pandas is more efficient than Numpy in dealing with files.

In [9]:
fname = "D:\\Courses\\Hesham Assem\\New folder\\file1.txt"
dtype1  =  dtype([('gender',  '|S1'),  ('height',  'f8')])
a = loadtxt(fname, dtype=dtype1, skiprows=9, usecols=(1,3)) # skiprows: to skip first 9 rows and return row = 10.
# usecols: to return column number 2 and 4. 
print(a)

[(b'F', 1.68) (b'F', 1.56) (b'F', 1.64) (b'M', 1.63) (b'M', 1.67)
 (b'F', 1.59)]


In [2]:
a,b,c = loadtxt("D:\\Courses\\Hesham Assem\\New folder\\file2.txt", unpack=True,skiprows=3)  # unpack = true => a,b,c to deal with columns.
print(a)
print(b)
print(c)

[1890. 1900. 1910. 1920. 1930.]
[26.1 25.9 25.1 24.6 24.3]
[22.  21.9 21.6 21.2 21.3]


In [3]:
data = genfromtxt("D:\\Courses\\Hesham Assem\\New folder\\file3.txt",  skip_header=1, dtype=[('student','u8'),
('gender','S1'),('black','f8'),('colour','f8')],delimiter=',', missing_values='X')
# skip_header = skiprows.
# delimiter: separator = ','
print(data)

[(1, b'F', 18.72, 31.11) (2, b'F', 21.14, 52.47) (3, b'F', 19.38, 33.9 )]


In [5]:
x = array('2023-12-10', dtype=datetime64)
print(x)
print('-------------------------')

2023-12-10
-------------------------


In [7]:
x = datetime64('2023-12-10')
y = x + arange(12)
print(x)
print('-------------------------')
print(y)

2023-12-10
-------------------------
['2023-12-10' '2023-12-11' '2023-12-12' '2023-12-13' '2023-12-14'
 '2023-12-15' '2023-12-16' '2023-12-17' '2023-12-18' '2023-12-19'
 '2023-12-20' '2023-12-21']


In [8]:
x = datetime64('2023-12-10')
y = x - arange(12)
print(x)
print('-------------------------')
print(y)

2023-12-10
-------------------------
['2023-12-10' '2023-12-09' '2023-12-08' '2023-12-07' '2023-12-06'
 '2023-12-05' '2023-12-04' '2023-12-03' '2023-12-02' '2023-12-01'
 '2023-11-30' '2023-11-29']


In [10]:
x = datetime64('2023-12-10')
y = datetime64('2022-09-21')
z = x-y
print(x)
print('-------------------------')
print(y)
print('-------------------------')
print(z)

2023-12-10
-------------------------
2022-09-21
-------------------------
445 days


In [11]:
x = fromfunction(lambda i: i**3, (10,))
print(x)
print('-------------------------')

[  0.   1.   8.  27.  64. 125. 216. 343. 512. 729.]
-------------------------


In [12]:
x = fromfunction(lambda i: 3 * (i+5)**3, (10,))
print(x)
print('-------------------------')

[ 375.  648. 1029. 1536. 2187. 3000. 3993. 5184. 6591. 8232.]
-------------------------


In [13]:
x = fromfunction(lambda i,j: i+j, (4,5))
print(x)
print('-------------------------')

[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]]
-------------------------


In [15]:
x = fromfunction(lambda i,j: 3*i*j, (4,5))
print(x)
print('-------------------------')

[[ 0.  0.  0.  0.  0.]
 [ 0.  3.  6.  9. 12.]
 [ 0.  6. 12. 18. 24.]
 [ 0.  9. 18. 27. 36.]]
-------------------------


In [16]:
x = fromfunction(lambda i,j,k: i+j+k, (2,3,4))
print(x)
print('-------------------------')

[[[0. 1. 2. 3.]
  [1. 2. 3. 4.]
  [2. 3. 4. 5.]]

 [[1. 2. 3. 4.]
  [2. 3. 4. 5.]
  [3. 4. 5. 6.]]]
-------------------------


In [17]:
x = fromfunction(lambda i,j,k: (2*i)+(j**2)*k, (2,3,4))
print(x)
print('-------------------------')

[[[ 0.  0.  0.  0.]
  [ 0.  1.  2.  3.]
  [ 0.  4.  8. 12.]]

 [[ 2.  2.  2.  2.]
  [ 2.  3.  4.  5.]
  [ 2.  6. 10. 14.]]]
-------------------------


In [21]:
def  powers(i):
    i  =  i**2
    return i
x = fromfunction(powers, (9,), dtype=int)
print(x)
print('-------------------------')

[ 0  1  4  9 16 25 36 49 64]
-------------------------


In [22]:
def powers(i,j):
    i = i**j
    return i
x = fromfunction(powers, (4,5), dtype=int)
print(x)
print('-------------------------')

[[ 1  0  0  0  0]
 [ 1  1  1  1  1]
 [ 1  2  4  8 16]
 [ 1  3  9 27 81]]
-------------------------


In [23]:
m,n = 20, 5
def f(i):
    return (i % n == 0)
x = fromfunction(f, (m,), dtype=int)
print(x)
print('-------------------------')

[ True False False False False  True False False False False  True False
 False False False  True False False False False]
-------------------------
